const Graces = {
  'Carência ANS': {
    id: 1,
    name: 'Carência ANS',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 30,
    grace_period_exam: 180,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 300,
    grace_period_exam_special_I: 180,
    grace_period_therapy: 180,
    grace_period_ambulatory_procedures: 180,
    grace_period_exam_special_II: 180,
    grace_period_admissions: 180
  },
  'Carência PRS II': {
    id: 2,
    name: 'Carência PRS II',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 1,
    grace_period_exam: 1,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 300,
    grace_period_exam_special_I: 1,
    grace_period_therapy: 1,
    grace_period_ambulatory_procedures: 1,
    grace_period_exam_special_II: 1,
    grace_period_admissions: 1
  },
  'Carência SAMI': {
    id: 3,
    name: 'Carência SAMI',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 30,
    grace_period_exam: 30,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 300,
    grace_period_exam_special_I: 180,
    grace_period_therapy: 30,
    grace_period_ambulatory_procedures: 180,
    grace_period_exam_special_II: 180,
    grace_period_admissions: 180
  },
  'Carência Portabilidade': {
    id: 4,
    name: 'Carência Portabilidade',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 1,
    grace_period_exam: 1,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 1,
    grace_period_exam_special_I: 1,
    grace_period_therapy: 1,
    grace_period_ambulatory_procedures: 1,
    grace_period_exam_special_II: 1,
    grace_period_admissions: 1
  },
  'Carência PRS I': {
    id: 5,
    name: 'Carência PRS I',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 15,
    grace_period_exam: 15,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 300,
    grace_period_exam_special_I: 15,
    grace_period_therapy: 15,
    grace_period_ambulatory_procedures: 90,
    grace_period_exam_special_II: 90,
    grace_period_admissions: 120
  },
  'Carência PME Porte II': {
    id: 6,
    name: 'Carência PME Porte II',
    start_at: '2021-03-04',
    stop_at: '2099-12-31',
    grace_period_appointment: 1,
    grace_period_exam: 1,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 1,
    grace_period_exam_special_I: 1,
    grace_period_therapy: 1,
    grace_period_ambulatory_procedures: 1,
    grace_period_exam_special_II: 1,
    grace_period_admissions: 1
  },
  'Carência PRS III': {
    id: 7,
    name: 'Carência PRS III',
    start_at: '2021-10-04',
    stop_at: '2099-10-04',
    grace_period_appointment: 1,
    grace_period_exam: 1,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 180,
    grace_period_exam_special_I: 1,
    grace_period_therapy: 1,
    grace_period_ambulatory_procedures: 180,
    grace_period_exam_special_II: 1,
    grace_period_admissions: 1
  },
  'Carência PRS IV': {
    id: 8,
    name: 'Carência PRS IV',
    start_at: '2021-10-14',
    stop_at: '2099-10-14',
    grace_period_appointment: 1,
    grace_period_exam: 1,
    grace_period_hospitalization: 1,
    grace_period_childbirth: 1,
    grace_period_exam_special_I: 1,
    grace_period_therapy: 1,
    grace_period_ambulatory_procedures: 1,
    grace_period_exam_special_II: 1,
    grace_period_admissions: 1
  }
}

module.exports = { Graces }
